// <auto-generated />
using System;
using Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    partial class JustBlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7109d8d6-464d-4ff9-bfbb-62c83c9788c3"),
                            Description = "Transfer News",
                            Name = "Transfer News",
                            UrlSlug = "transfer-news"
                        },
                        new
                        {
                            Id = new Guid("fd264eff-b43e-4a61-84a2-63dc29ce38cb"),
                            Description = "Premier League",
                            Name = "Premier League",
                            UrlSlug = "premier-league"
                        },
                        new
                        {
                            Id = new Guid("af301972-f954-4319-ad44-3b85f5294e61"),
                            Description = "Champions League",
                            Name = "Champions League",
                            UrlSlug = "champions-league"
                        },
                        new
                        {
                            Id = new Guid("6dedb11c-5d41-48f3-81dd-d3d5ff0c7a3e"),
                            Description = "Bundesliga",
                            Name = "Bundesliga",
                            UrlSlug = "bundesliga"
                        },
                        new
                        {
                            Id = new Guid("8ee8e5b7-ff33-460d-8a5c-2385518a2845"),
                            Description = "Serie A",
                            Name = "Serie A",
                            UrlSlug = "serie-a"
                        },
                        new
                        {
                            Id = new Guid("44fcbdd6-262c-408f-927a-88a3d39b482d"),
                            Description = "Laliga",
                            Name = "Laliga",
                            UrlSlug = "la-liga"
                        });
                });

            modelBuilder.Entity("Entity.Entity.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("575e2dd9-3be4-4bc1-bd23-329716c917a2"),
                            CommentHeader = "Good",
                            CommentText = "Very good",
                            CommentTime = new DateTime(2022, 11, 13, 20, 15, 42, 829, DateTimeKind.Local).AddTicks(2583),
                            Email = "brucelee@mail.com",
                            Name = "Bruce Lee",
                            PostId = new Guid("82a43557-d760-4e5e-88c0-4835f36cfb17")
                        },
                        new
                        {
                            Id = new Guid("2a7faf4c-e357-4e9d-b453-6ad0f858e9d9"),
                            CommentHeader = "Good",
                            CommentText = "Very very good",
                            CommentTime = new DateTime(2022, 11, 13, 20, 15, 42, 829, DateTimeKind.Local).AddTicks(2614),
                            Email = "taiobe@mail.com",
                            Name = "Tai OBE",
                            PostId = new Guid("54606ea0-ec4f-4ec4-9181-8153e1a2332e")
                        },
                        new
                        {
                            Id = new Guid("4dc88bb0-6d6d-440a-adfe-c87600e721d7"),
                            CommentHeader = "Good",
                            CommentText = "Very very very good",
                            CommentTime = new DateTime(2022, 11, 13, 20, 15, 42, 829, DateTimeKind.Local).AddTicks(2626),
                            Email = "huongvip@mail.com",
                            Name = "Huong VIP",
                            PostId = new Guid("94475a71-ad8e-438f-b917-3c4a667f44ef")
                        });
                });

            modelBuilder.Entity("Entity.Entity.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Modified")
                        .HasColumnType("bit");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<int>("RateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("82a43557-d760-4e5e-88c0-4835f36cfb17"),
                            CategoryId = new Guid("fd264eff-b43e-4a61-84a2-63dc29ce38cb"),
                            Modified = false,
                            PostContent = "Tottenham Hotspur underlined their credentials as a team capable of a Premier League title challenge with a confident 4-1 defeat of Southampton to get their campaign up and running on Saturday.The hosts fell behind to a James Ward - Prowse volley in the 12th minute but dominated throughout with goals by Ryan Sessegnon,Eric Dier and Dejan Kulusevski sealing the win.Southampton's lead lasted only nine minutes before Sessegnon powered a header past Southampton's Premier League debutant keeper Gavin Bazunu from Kulusevski's cross.",
                            PostedOn = new DateTime(2022, 8, 13, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Tottenham Hotspur underlined their credentials as a team capable of a Premier League title challenge with a confident 4-1 defeat of Southampton to get their campaign up and running on Saturday.",
                            Title = "Tottenham crush Southampton for impressive opening win",
                            TotalRate = 10,
                            UrlSlug = "tottenham-crush-southampton-for-impressive-opening-win",
                            ViewCount = 1000
                        },
                        new
                        {
                            Id = new Guid("54606ea0-ec4f-4ec4-9181-8153e1a2332e"),
                            CategoryId = new Guid("fd264eff-b43e-4a61-84a2-63dc29ce38cb"),
                            Modified = false,
                            PostContent = "Liverpool midfielder Thiago Alcantara will be out of action for up to six weeks because of injury, sources have told ESPN.The Spain international limped off the pitch early in the second half with a suspected hamstring strain during Saturday's 2-2 Premier League draw at Fulham.Thiago's injury comes at a bad time for Liverpool, who are still without midfielders Alex Oxlade-Chamberlain and Curtis Jones.This isn't a good situation. I don't like it at all.We have to see how we react on that,but for sure not panic,  Liverpool coach Jurgen Klopp said.The transfer window closes on Sept. 1 but Klopp indicated Liverpool will not make a rash decision regarding signing new players.",
                            PostedOn = new DateTime(2022, 8, 13, 20, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Liverpool midfielder Thiago Alcantara will be out of action for up to six weeks because of injury, sources have told ESPN.",
                            Title = "Liverpool's Thiago Alcantara out for up to six weeks - sources",
                            TotalRate = 9,
                            UrlSlug = "liverpools-thiago-alcantara-out-for-up-to-six-weeks-sources",
                            ViewCount = 800
                        },
                        new
                        {
                            Id = new Guid("94475a71-ad8e-438f-b917-3c4a667f44ef"),
                            CategoryId = new Guid("fd264eff-b43e-4a61-84a2-63dc29ce38cb"),
                            Modified = false,
                            PostContent = "Oddsmakers have pegged the quest for the Premier League title as a two-horse race, with defending-champion Manchester City and Liverpool separated from the pack.Man City,who have won four of the past five EPL titles,are the odds favorite to win it again,listed at - 165 at Caesars Sportsbooks.Liverpool,last season's runner-ups, are +200.The gap between the two top clubs and the rest of the table is significant,according to oddsmakers.Man City and Liverpool are the only two teams with single - digit odds.Tottenham,at + 1,400,and Chelsea,at + 1,600,are next but are a ways down oddsboards.Tottenham,however,have attracted the most bets and are the most wagered to win the league title at Caesars Sportsbook,but it'll be a tall task to unseat Man City.Man City added elite striker Erling Haaland in the offseason,bolstering Pep Guardiola's already potent roster that posted 93 points en route to last years title.It was the sixth - most points in league history.Liverpool,though,finished just one point behind and notched a victory over Man City last week in the FA Community Shield.Arsenal,who kick off the season Friday against Crystal Palace,are + 2,800,and Manchester United are + 3,500.Man United's preseason title odds are the longest they've been in over a decade,according to sports betting archive SportsOddsHistory.com.Bournemouth and Fulham,at 1,500 - 1 and 1,000 - 1 respectively,are the longest shots on the board at Caesars Sportsbook.",
                            PostedOn = new DateTime(2022, 8, 12, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Oddsmakers have pegged the quest for the Premier League title as a two-horse race, with defending-champion Manchester City and Liverpool separated from the pack.",
                            Title = "Man City and Liverpool ahead of the chasing pack in Premier League title race, oddsmakers say",
                            TotalRate = 9,
                            UrlSlug = "man-city-and-liverpool-ahead-of-the-chasing-pack-in-premier-league-title-race-od",
                            ViewCount = 800
                        },
                        new
                        {
                            Id = new Guid("70844495-31db-43d2-b5b0-ce2e2da2ccfa"),
                            CategoryId = new Guid("7109d8d6-464d-4ff9-bfbb-62c83c9788c3"),
                            Modified = false,
                            PostContent = "Tottenham are closing in on the signing of versatile Inter winger Ivan Perisic on a two-year deal, 90min understands.The 33 - year - old is out of contract at San Siro this summer and has long been linked with a move away from the club.Perisic has previously worked with Tottenham head coach Antonio Conte at Inter,winning the Serie A title under him,and 90min has learned that a reunion in north London is close to completion.Indeed,sources have told 90min that Perisic,who famously scored in Croatia's 2-1 win over England in the 2018 World Cup semi-final, has agreed a two-year deal and will undergo a medical next week.He also fielded offers from Chelsea and Juventus this summer, as well as a bid from the Nerazzurri to extend his contract,but the chance to pair up with Conte - who confirmed to the club in a meeting in Turin that he intends to remain in charge despite links with PSG - appears to have been too good of an opportunity to turn down.",
                            PostedOn = new DateTime(2022, 8, 11, 11, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Tottenham are closing in on the signing of versatile Inter winger Ivan Perisic on a two-year deal",
                            Title = "Tottenham close to signing Ivan Perisic from Inter",
                            TotalRate = 9,
                            UrlSlug = "tottenham-close-to-signing-ivan-perisic-from-inter",
                            ViewCount = 800
                        },
                        new
                        {
                            Id = new Guid("c23d7677-ab19-4143-810c-4f7bef4cca87"),
                            CategoryId = new Guid("7109d8d6-464d-4ff9-bfbb-62c83c9788c3"),
                            Modified = false,
                            PostContent = "Bayern Munich CEO Oliver Kahn has this time declined to discuss a transfer for Tottenham striker Harry Kane.The former goalkeeper recently described Kane as a 'dream of the future', while Bayern boss Julian Naglesmann has also gone public with his admiration of the striker - prompting a frustrated response from Spurs boss Antonio Conte.Seemingly concerned about upsetting Conte once again, Kahn declined to get drawn into a conversation about Kane when asked for an update on Bayern's interest.I can just say that Harry Kane is an outstanding striker who is now under contract at Tottenham, Kahn told Bild.Conte has described Bayern's interest as 'only rumours' and reiterated the club's desire to keep Kane around for the foreseeable future.",
                            PostedOn = new DateTime(2022, 8, 12, 14, 10, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Bayern Munich CEO Oliver Kahn has this time declined to discuss a transfer for Tottenham striker Harry Kane.",
                            Title = "Harry Kane: Bayern Munich CEO refuses to discuss move for 'outstanding' Tottenham striker",
                            TotalRate = 9,
                            UrlSlug = "harry-kane-bayern-munich-ceo-refuses-to-discuss-move-for-outstanding-tottenham",
                            ViewCount = 900
                        },
                        new
                        {
                            Id = new Guid("3cb9eb48-216f-41f5-9752-e2c36a2f1c13"),
                            CategoryId = new Guid("7109d8d6-464d-4ff9-bfbb-62c83c9788c3"),
                            Modified = false,
                            PostContent = "Bayern Munich have confirmed the signing of Sadio Mane from Liverpool on a three-year deal.Mane departs Anfield after six glorious years in which he won every honour available to him,including the Champions League in 2019 and Premier League one year later.The forward had long been expected to leave this summer with Bayern kicking off negotiations towards the end of last season.Eventually a deal was struck and 90min understands that Mane agreed to waive some potential future earnings to help smooth negotiations along.I'm really happy to finally be at FC Bayern in Munich, Mane said. We spoke a lot and I felt big interest from this great club right from the beginning, so for me there were no doubts. Its the right time for this challenge.I want to achieve a lot with this club, in Europe too. During my time in Salzburg I watched a lot of Bayern games - I really like this club!Bayern CEO Oliver Kahn added: We are delighted that weve been able to recruit Sadio Mane for FC Bayern. With his outstanding performances and his great successes at the highest international level over many years, there are very few players like him in the world.We re sure that Sadio Mane will delight our fans in the coming years with his spectacular style of play. He s ambitious and eager to win more titles. This package is very strong. With players like him at FC Bayern, all the biggest goals are possible.",
                            PostedOn = new DateTime(2022, 7, 24, 5, 28, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Bayern Munich have confirmed the signing of Sadio Mane from Liverpool on a three-year deal.",
                            Title = "Bayern Munich confirm Sadio Mane signing",
                            TotalRate = 9,
                            UrlSlug = "bayern-munich-confirm-sadio-mane-signing",
                            ViewCount = 900
                        },
                        new
                        {
                            Id = new Guid("472942a5-a3ad-4ef0-be6f-a73ae48028e4"),
                            CategoryId = new Guid("7109d8d6-464d-4ff9-bfbb-62c83c9788c3"),
                            Modified = false,
                            PostContent = "Comfortably the two best sides in England went punch for punch on the pitch last season, and Manchester City and Liverpool are now doing the same off it through the respective arrivals of Erling Haaland and Darwin Nunez, with neither Pep Guardiola or Jurgen Klopp willing to give each other an inch for fear of the other taking a mile in what looks set once again to be a two-horse race in the Premier League.Manchester City signed a big,fast,prolific central striker in an attempt to adapt,develop or at least offer an alternative to their style of football to steal a march on Liverpool.Only for Liverpool to respond in kind, signing their own big, fast, prolific central striker.Straight comparisons between the pair are reductive given they've played for different clubs with different players in different divisions. What we do know is that they can score goals and – given the competition to sign Haaland and the £85m needed for Nunez – City and Liverpool have little doubt they will continue to do so.One point was all that could separate City and Liverpool last season, with final day drama adding to what was already one of the great title races in Premier League history.Confirmation of their marquee summer signings leads to questions as to whether either has given one team the edge, or if Nunez and Haaland will instead cancel each other out, with respective one per cent improvements simply maintaining the extraordinarily well - matched dominance of these two wonderful football teams.",
                            PostedOn = new DateTime(2022, 7, 9, 16, 48, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Comfortably the two best sides in England went punch for punch on the pitch last season, and Manchester City and Liverpool are now doing the same off it through the respective arrivals of Erling Haaland and Darwin Nunez, with neither Pep Guardiola or Jurgen Klopp willing to give each other an inch for fear of the other taking a mile in what looks set once again to be a two-horse race in the Premier League.",
                            Title = "Liverpool forced into Darwin Nunez move as Erling Haaland raises Man City ceiling",
                            TotalRate = 9,
                            UrlSlug = "liverpool-forced-into-darwin-nunez-move-as-erling-haaland-raises-man-city-ceiling",
                            ViewCount = 600
                        },
                        new
                        {
                            Id = new Guid("90086993-0826-437c-9aee-993939c11a5e"),
                            CategoryId = new Guid("af301972-f954-4319-ad44-3b85f5294e61"),
                            Modified = false,
                            PostContent = "Manchester City chief executive Ferran Soriano has insisted that the is ‘not obsessed’ with winning the Champions League but claims Real Madrid were ‘a bit lucky’ last season.Real lifted their 14th European crown in May after beating Liverpool in the final.They had already beaten City,Chelsea and Paris Saint - Germain in previous knockout rounds and needed to come from behind in all three ties in order to progress.Discussing Real’s success as well as his own club’s ambitions,Soriano told the Dr.Football podcast: “The Champions League is a trophy that we want,but we know that it is subject to a bit of luck and we are not obsessed.“People talk today about the success that Madrid have had in recent years,and I think it would be fair to say that they were a bit lucky.Perhaps I could say that they deserved to lose against PSG,against Chelsea,against us or against Liverpool.”",
                            PostedOn = new DateTime(2022, 6, 25, 23, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Manchester City chief executive Ferran Soriano has insisted that the is ‘not obsessed’ with winning the Champions League but claims Real Madrid were ‘a bit lucky’ last season.",
                            Title = "Man City chief executive claims Real Madrid were 'lucky' in Champions League",
                            TotalRate = 9,
                            UrlSlug = "man-city-chief-executive-claims-real-madrid-were-lucky-in-champions-league",
                            ViewCount = 700
                        },
                        new
                        {
                            Id = new Guid("f30a160c-5c70-4042-ad83-5c128fbeb0f5"),
                            CategoryId = new Guid("af301972-f954-4319-ad44-3b85f5294e61"),
                            Modified = false,
                            PostContent = "UEFA president Aleksander Ceferin has hit back at managers like Pep Guardiola and Jurgen Klopp over their fixture congestion complaints.Guardiola and Klopp have been hyper critical of the football calendar over the last season,with the former even hinting that striking may be the best option to have changes be implemented:The problem is the fixtures. The calendar, 365 days a year with international duties for the national team, huge competitions with a lot of games. The players have two or three weeks of holiday in the summer and it’s the season again. This is too much.Should the players and the managers be all together together and make a strike, or something, because just through words it's not going to be solved? For FIFA, the Premier League, the broadcasters…the business is more important than the welfare.",
                            PostedOn = new DateTime(2022, 5, 13, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "UEFA president Aleksander Ceferin has hit back at managers like Pep Guardiola and Jurgen Klopp over their fixture congestion complaints.",
                            Title = "UEFA president hits back at Jurgen Klopp & Pep Guardiola over fixture congestion complaints",
                            TotalRate = 9,
                            UrlSlug = "uefa-president-hits-back-at-jurgen-klopp-pep-guardiola-over-fixture-congestion",
                            ViewCount = 500
                        },
                        new
                        {
                            Id = new Guid("42b20213-e508-4220-b509-5cf176ee32ad"),
                            CategoryId = new Guid("af301972-f954-4319-ad44-3b85f5294e61"),
                            Modified = false,
                            PostContent = "The road to the 2022/23 Champions League has started with some of the earliest qualifying matches being scheduled.A large number of Europe's elite clubs have qualified already through league position, though a fair few teams can still book their spot in next season's competition by winning qualifiers throughout the summer.Here are all the dates you need in the build - up to the 2022 / 23 Champions League.",
                            PostedOn = new DateTime(2022, 7, 13, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "The road to the 2022/23 Champions League has started with some of the earliest qualifying matches being scheduled.",
                            Title = "2022/23 Champions League: Qualification dates, draws & schedule",
                            TotalRate = 9,
                            UrlSlug = "2022-23-champions-league-qualification-dates-draws-schedule",
                            ViewCount = 800
                        },
                        new
                        {
                            Id = new Guid("7e8045c8-c6da-40c0-81bf-4fe0be6c730b"),
                            CategoryId = new Guid("6dedb11c-5d41-48f3-81dd-d3d5ff0c7a3e"),
                            Modified = false,
                            PostContent = "Bayern Munich forward Sadio Mane has claimed that his new employers would beat former side Liverpool if the two faced off in the Champions League.Bayern have bested Liverpool just once in the pair's nine meetings and most recently fell 3-1 at the Allianz Arena in March 2019, a game which featured two goals from Mane.The Segenal star's first strike saw him turn Manuel Neuer inside out before firing into the back of the net, with Mane later describing it as one of his two favourite goals from his time with Liverpool.In the Bundesliga newsletter,Mane was asked whether he would still describe his goal against Bayern as his favourite,and he confessed that his new relationship with Neuer has seen him demote the strike to second.I said maybe my favourite but now I would say second favourite goal, not my first, because he's my team-mate, Mane laughed. No, I'm joking… of course, I think it was a good goal, kind of a good goal. We had a good game.This is behind us. If we re going to meet again, of course as Bayern Munich wd beat Liverpool.",
                            PostedOn = new DateTime(2022, 8, 5, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Bayern Munich forward Sadio Mane has claimed that his new employers would beat former side Liverpool if the two faced off in the Champions League.",
                            Title = "Sadio Mane: 'Of course' Bayern Munich would beat Liverpool",
                            TotalRate = 9,
                            UrlSlug = "sadio-mane-of-course-bayern-munich-would-beat-liverpool",
                            ViewCount = 600
                        },
                        new
                        {
                            Id = new Guid("ce5ebd4b-0bc9-46b3-b223-c5c9b7c53b7e"),
                            CategoryId = new Guid("6dedb11c-5d41-48f3-81dd-d3d5ff0c7a3e"),
                            Modified = false,
                            PostContent = "Borussia Dortmund have confirmed that Sebastien Haller will begin chemotherapy treatment as part of his battle against a malignant testicular tumour.The new signing recently underwent surgery to remove a tumour which sporting director Sebastian Kehl confirmed went positively,adding that the Ivory Coast international will be out of action for the next 'few months'.Kehl has now offered a further update, revealing that Haller will soon begin chemotherapy.Sebastien will now receive the best possible treatment, Kehl said. The chances of recovery are very good.We wish him and his family a lot of strength and optimism and our thoughts are with him during this difficult time.",
                            PostedOn = new DateTime(2022, 7, 13, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Borussia Dortmund have confirmed that Sebastien Haller will begin chemotherapy treatment as part of his battle against a malignant testicular tumour.",
                            Title = "Sebastien Haller to start chemotherapy for malignant testicular tumour",
                            TotalRate = 9,
                            UrlSlug = "sebastien-haller-to-start-chemotherapy-for-malignant-testicular-tumour",
                            ViewCount = 500
                        },
                        new
                        {
                            Id = new Guid("2c7f0720-cdd9-4a47-818f-25fed485ffbf"),
                            CategoryId = new Guid("6dedb11c-5d41-48f3-81dd-d3d5ff0c7a3e"),
                            Modified = false,
                            PostContent = "Bayern Munich made an intimidating start to their latest Bundesliga title defence by smashing Europa League holders Eintracht Frankfurt 6-1 at Deutsche Bank Park on Friday night.Julian Nagelsmann's side finished eight points clear of closest competitors Borussia Dortmund to win the league last season, while Frankfurt weren't in the conversation despite their success in Europe.Bayern were 2 - 0 up inside ten minutes thanks to strikes from Joshua Kimmich and Benjamin Pavard and added another three before half time.Sadio Mane struck for the first time in the Bundesliga by heading in from Serge Gnabry's flick before youngster Jamal Musiala tapped in from close range. Gnabry soon sent the two teams into the interval with the game's fifth strike.Manuel Neuer did offer Frankfurt a crumb of comfort, dithering on the ball for too long and allowing Randal Kolo Muani to nip in and score a consolation on debut, but that was as good as it ever got for the hosts.Musiala later scrambled through the hosts' defence to slide in Bayern's sixth, topping off an impressive night's work for the reigning German champions.",
                            PostedOn = new DateTime(2022, 8, 13, 15, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Bayern Munich made an intimidating start to their latest Bundesliga title defence by smashing Europa League holders Eintracht Frankfurt 6-1 at Deutsche Bank Park on Friday night.",
                            Title = "Eintracht Frankfurt 1-6 Bayern Munich: Champions make imposing start to Bundesliga season",
                            TotalRate = 9,
                            UrlSlug = "eintracht-frankfurt-1-6-bayern-munich-champions-make-imposing-start-to-bundeslig",
                            ViewCount = 900
                        },
                        new
                        {
                            Id = new Guid("5e08bde8-c46b-4df0-a74e-66acecaf62a8"),
                            CategoryId = new Guid("8ee8e5b7-ff33-460d-8a5c-2385518a2845"),
                            Modified = false,
                            PostContent = "Roma striker Tammy Abraham insists he has never looked back following his departure from Chelsea last summer.The Blues academy graduate was offloaded in a £34m deal to help make room for the signing of Romelu Lukaku, who has since returned to Inter on a season - long loan after his £97.5m arrival yielded just eight Premier League goals.While Lukaku was struggling, Abraham settled in quickly at Roma and ended his debut season with 27 goals in 53 games in all competitions, helping them to Europa Conference League glory.The numbers speak for themselves, and Abraham recently told Corriere dello Sport that he has zero regrets about his departure from Chelsea.",
                            PostedOn = new DateTime(2022, 8, 10, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Roma striker Tammy Abraham insists he has never looked back following his departure from Chelsea last summer.",
                            Title = "Tammy Abraham insists he has 'no regrets' over Chelsea departure",
                            TotalRate = 9,
                            UrlSlug = "tammy-abraham-insists-he-has-no-regrets-over-chelsea-departure",
                            ViewCount = 800
                        },
                        new
                        {
                            Id = new Guid("bf180548-f7d9-42b8-896d-ab6fc4ddcde4"),
                            CategoryId = new Guid("8ee8e5b7-ff33-460d-8a5c-2385518a2845"),
                            Modified = false,
                            PostContent = "Paulo Dybala has denied that money played a role in his Juventus departure, with the new Roma forward claiming that he exited for footballing reasons.Back in March it was announced that Dybala would be leaving Juve at the end of his contract this summer and he had seemed set to join Inter,until I Giallorossi swooped in to secure his services.The Argentine was unveiled as a Roma player on Tuesday and,during a press conference,he opened up on the process of departing the Allianz Stadium.I think the director [Maurizio] Arrivabene was very clear in his statements: we had an agreement to sign in October, then [the club] asked to wait, he explained.",
                            PostedOn = new DateTime(2022, 7, 13, 8, 8, 8, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Paulo Dybala has denied that money played a role in his Juventus departure, with the new Roma forward claiming that he exited for footballing reasons.",
                            Title = "Paulo Dybala explains why he left Juventus for Roma",
                            TotalRate = 9,
                            UrlSlug = "paulo-dybala-explains-why-he-left-juventus-for-roma",
                            ViewCount = 700
                        });
                });

            modelBuilder.Entity("Entity.Entity.PostTagMap", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTagMap", (string)null);

                    b.HasData(
                        new
                        {
                            PostId = new Guid("82a43557-d760-4e5e-88c0-4835f36cfb17"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("54606ea0-ec4f-4ec4-9181-8153e1a2332e"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("94475a71-ad8e-438f-b917-3c4a667f44ef"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("70844495-31db-43d2-b5b0-ce2e2da2ccfa"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("c23d7677-ab19-4143-810c-4f7bef4cca87"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("472942a5-a3ad-4ef0-be6f-a73ae48028e4"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("f30a160c-5c70-4042-ad83-5c128fbeb0f5"),
                            TagId = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f")
                        },
                        new
                        {
                            PostId = new Guid("70844495-31db-43d2-b5b0-ce2e2da2ccfa"),
                            TagId = new Guid("ebf175db-f1ae-4989-83b7-a1c828bcef8c")
                        },
                        new
                        {
                            PostId = new Guid("c23d7677-ab19-4143-810c-4f7bef4cca87"),
                            TagId = new Guid("ebf175db-f1ae-4989-83b7-a1c828bcef8c")
                        },
                        new
                        {
                            PostId = new Guid("3cb9eb48-216f-41f5-9752-e2c36a2f1c13"),
                            TagId = new Guid("ebf175db-f1ae-4989-83b7-a1c828bcef8c")
                        },
                        new
                        {
                            PostId = new Guid("472942a5-a3ad-4ef0-be6f-a73ae48028e4"),
                            TagId = new Guid("ebf175db-f1ae-4989-83b7-a1c828bcef8c")
                        },
                        new
                        {
                            PostId = new Guid("c23d7677-ab19-4143-810c-4f7bef4cca87"),
                            TagId = new Guid("9257978f-8a06-49bb-ac8f-7b4d35640dbf")
                        },
                        new
                        {
                            PostId = new Guid("3cb9eb48-216f-41f5-9752-e2c36a2f1c13"),
                            TagId = new Guid("9257978f-8a06-49bb-ac8f-7b4d35640dbf")
                        },
                        new
                        {
                            PostId = new Guid("7e8045c8-c6da-40c0-81bf-4fe0be6c730b"),
                            TagId = new Guid("9257978f-8a06-49bb-ac8f-7b4d35640dbf")
                        },
                        new
                        {
                            PostId = new Guid("ce5ebd4b-0bc9-46b3-b223-c5c9b7c53b7e"),
                            TagId = new Guid("9257978f-8a06-49bb-ac8f-7b4d35640dbf")
                        },
                        new
                        {
                            PostId = new Guid("2c7f0720-cdd9-4a47-818f-25fed485ffbf"),
                            TagId = new Guid("9257978f-8a06-49bb-ac8f-7b4d35640dbf")
                        },
                        new
                        {
                            PostId = new Guid("90086993-0826-437c-9aee-993939c11a5e"),
                            TagId = new Guid("f562d1b0-02db-4c1c-a4db-3e51c250f8a3")
                        },
                        new
                        {
                            PostId = new Guid("f30a160c-5c70-4042-ad83-5c128fbeb0f5"),
                            TagId = new Guid("f562d1b0-02db-4c1c-a4db-3e51c250f8a3")
                        },
                        new
                        {
                            PostId = new Guid("42b20213-e508-4220-b509-5cf176ee32ad"),
                            TagId = new Guid("f562d1b0-02db-4c1c-a4db-3e51c250f8a3")
                        },
                        new
                        {
                            PostId = new Guid("5e08bde8-c46b-4df0-a74e-66acecaf62a8"),
                            TagId = new Guid("5c717df9-2347-4c67-be32-3474ccebc287")
                        },
                        new
                        {
                            PostId = new Guid("bf180548-f7d9-42b8-896d-ab6fc4ddcde4"),
                            TagId = new Guid("5c717df9-2347-4c67-be32-3474ccebc287")
                        },
                        new
                        {
                            PostId = new Guid("82a43557-d760-4e5e-88c0-4835f36cfb17"),
                            TagId = new Guid("4fa08da5-df70-42c8-96b2-7ad93986c3dd")
                        },
                        new
                        {
                            PostId = new Guid("70844495-31db-43d2-b5b0-ce2e2da2ccfa"),
                            TagId = new Guid("4fa08da5-df70-42c8-96b2-7ad93986c3dd")
                        },
                        new
                        {
                            PostId = new Guid("54606ea0-ec4f-4ec4-9181-8153e1a2332e"),
                            TagId = new Guid("ed9fda2f-8e59-443d-8a79-2991366b27b9")
                        },
                        new
                        {
                            PostId = new Guid("94475a71-ad8e-438f-b917-3c4a667f44ef"),
                            TagId = new Guid("ed9fda2f-8e59-443d-8a79-2991366b27b9")
                        },
                        new
                        {
                            PostId = new Guid("472942a5-a3ad-4ef0-be6f-a73ae48028e4"),
                            TagId = new Guid("ed9fda2f-8e59-443d-8a79-2991366b27b9")
                        },
                        new
                        {
                            PostId = new Guid("94475a71-ad8e-438f-b917-3c4a667f44ef"),
                            TagId = new Guid("c51319df-22b7-4470-ab83-b559a8f5ee19")
                        },
                        new
                        {
                            PostId = new Guid("472942a5-a3ad-4ef0-be6f-a73ae48028e4"),
                            TagId = new Guid("c51319df-22b7-4470-ab83-b559a8f5ee19")
                        },
                        new
                        {
                            PostId = new Guid("90086993-0826-437c-9aee-993939c11a5e"),
                            TagId = new Guid("c51319df-22b7-4470-ab83-b559a8f5ee19")
                        });
                });

            modelBuilder.Entity("Entity.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("46118fe1-2d15-4c5b-82f9-bc2f19b4a7c3"),
                            ConcurrencyStamp = "7e877db7-2b78-4ff0-b66d-51de262a4d42",
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = new Guid("bf483ecf-7107-420a-a316-712160ae7e59"),
                            ConcurrencyStamp = "710acf93-de54-4cd3-8cb9-8393f54a0ced",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        },
                        new
                        {
                            Id = new Guid("81bd671f-2cb9-40e3-9245-5b37135b1bab"),
                            ConcurrencyStamp = "433f9919-e78f-447a-9650-63c4cc973422",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Entity.Entity.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Decription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("46b3e11a-7caa-4bbb-bca3-254baaed7c4f"),
                            Count = 1,
                            Decription = "Premier League",
                            Name = "epl",
                            UrlSlug = "epl"
                        },
                        new
                        {
                            Id = new Guid("ebf175db-f1ae-4989-83b7-a1c828bcef8c"),
                            Count = 2,
                            Decription = "Transfer News",
                            Name = "transfer",
                            UrlSlug = "transfer"
                        },
                        new
                        {
                            Id = new Guid("9257978f-8a06-49bb-ac8f-7b4d35640dbf"),
                            Count = 3,
                            Decription = "bundesliga",
                            Name = "bundesliga",
                            UrlSlug = "bundesliga"
                        },
                        new
                        {
                            Id = new Guid("f562d1b0-02db-4c1c-a4db-3e51c250f8a3"),
                            Count = 3,
                            Decription = "champions-league",
                            Name = "champions-league",
                            UrlSlug = "champions-league"
                        },
                        new
                        {
                            Id = new Guid("5c717df9-2347-4c67-be32-3474ccebc287"),
                            Count = 3,
                            Decription = "serie-a",
                            Name = "serie-a",
                            UrlSlug = "serie-a"
                        },
                        new
                        {
                            Id = new Guid("3c172200-28d2-4758-97df-d595384eb4f5"),
                            Count = 3,
                            Decription = "la-liga",
                            Name = "la-liga",
                            UrlSlug = "la-liga"
                        },
                        new
                        {
                            Id = new Guid("4fa08da5-df70-42c8-96b2-7ad93986c3dd"),
                            Count = 3,
                            Decription = "tot",
                            Name = "tot",
                            UrlSlug = "tot"
                        },
                        new
                        {
                            Id = new Guid("ed9fda2f-8e59-443d-8a79-2991366b27b9"),
                            Count = 3,
                            Decription = "liv",
                            Name = "liv",
                            UrlSlug = "liv"
                        },
                        new
                        {
                            Id = new Guid("c51319df-22b7-4470-ab83-b559a8f5ee19"),
                            Count = 3,
                            Decription = "mc",
                            Name = "mc",
                            UrlSlug = "mc"
                        },
                        new
                        {
                            Id = new Guid("6486ff2a-516c-4586-9668-0dfcf73027fb"),
                            Count = 3,
                            Decription = "chel",
                            Name = "chel",
                            UrlSlug = "chel"
                        },
                        new
                        {
                            Id = new Guid("559bfae1-02f5-4dcf-b8fe-76d3313d3894"),
                            Count = 3,
                            Decription = "lei",
                            Name = "lei",
                            UrlSlug = "lei"
                        },
                        new
                        {
                            Id = new Guid("963eac23-6a1f-46fc-bc67-49b1ebacd3ed"),
                            Count = 3,
                            Decription = "ars",
                            Name = "ars",
                            UrlSlug = "ars"
                        },
                        new
                        {
                            Id = new Guid("f3f34549-daa6-4556-aec4-01ecc41c7182"),
                            Count = 3,
                            Decription = "mu",
                            Name = "mu",
                            UrlSlug = "mu"
                        },
                        new
                        {
                            Id = new Guid("ae54c887-7a64-40eb-9d46-5c828491e348"),
                            Count = 3,
                            Decription = "bay",
                            Name = "bay",
                            UrlSlug = "bay"
                        },
                        new
                        {
                            Id = new Guid("a11e5689-b978-411a-aeae-5d427b4a80ef"),
                            Count = 3,
                            Decription = "real",
                            Name = "real",
                            UrlSlug = "real"
                        });
                });

            modelBuilder.Entity("Entity.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3b5d306-49b2-46b2-a345-fc9d644f6700"),
                            AboutMe = "Good",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c289feb5-f62a-49b3-85e4-27311e45b870",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brucelee@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Bruce Lee",
                            LockoutEnabled = false,
                            NormalizedUserName = "BRUCELEE",
                            PasswordHash = "AQAAAAEAACcQAAAAEO7K25flepdptFpJzbZZfRDM3k7tz6ejg4jbxejKd4ag5wBQ05B0rnyL3o8uWZtxEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e5ca526-afb9-43e4-9532-832b775de544",
                            TwoFactorEnabled = false,
                            UserName = "brucelee"
                        },
                        new
                        {
                            Id = new Guid("96513711-41f4-45d7-b234-769c2c402ec8"),
                            AboutMe = "Good",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01f2d6be-52d2-4bc1-b167-ea54da5c57f6",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brucelee2@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Bruce Lee 2",
                            LockoutEnabled = false,
                            NormalizedUserName = "BRUCELEE2",
                            PasswordHash = "AQAAAAEAACcQAAAAEBDOY6AQaGsFeOfA5Dss23Vhm5fvjmWkV/MeDJdUSPMkqYNxLqGlFBltQKlrzXdnbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61065969-bf1a-48bd-bc4d-1dd99f1d54b2",
                            TwoFactorEnabled = false,
                            UserName = "brucelee2"
                        },
                        new
                        {
                            Id = new Guid("ab517e6c-0ce4-485b-aace-de9a21b8d01b"),
                            AboutMe = "Good",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2cfdc98-1293-448b-8ea9-541f3e143fc8",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brucelee3@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Bruce Lee 3",
                            LockoutEnabled = false,
                            NormalizedUserName = "BRUCELEE3",
                            PasswordHash = "AQAAAAEAACcQAAAAEPsSD0QbOEd23E23MCeeN7AMPnU9ZhsWMcqhC40x3T1jDKRE+y+5ZFuuSuQEzO2tvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8bcc8ad9-f07f-4cda-b20c-98c21ce70dc8",
                            TwoFactorEnabled = false,
                            UserName = "brucelee3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ProviderKey");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e3b5d306-49b2-46b2-a345-fc9d644f6700"),
                            RoleId = new Guid("46118fe1-2d15-4c5b-82f9-bc2f19b4a7c3")
                        },
                        new
                        {
                            UserId = new Guid("96513711-41f4-45d7-b234-769c2c402ec8"),
                            RoleId = new Guid("bf483ecf-7107-420a-a316-712160ae7e59")
                        },
                        new
                        {
                            UserId = new Guid("ab517e6c-0ce4-485b-aace-de9a21b8d01b"),
                            RoleId = new Guid("81bd671f-2cb9-40e3-9245-5b37135b1bab")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("Entity.Entity.Comment", b =>
                {
                    b.HasOne("Entity.Entity.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Entity.Entity.Post", b =>
                {
                    b.HasOne("Entity.Entity.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entity.Entity.PostTagMap", b =>
                {
                    b.HasOne("Entity.Entity.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entity.Tag", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Entity.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Entity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Entity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Entity.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Entity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Entity.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Entity.Entity.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("Entity.Entity.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
